name: market_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  firebase_core: ^2.24.3
  firebase_auth: ^4.16.2
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.15.3
  equatable: ^2.0.5
  firebase_auth_web: ^5.4.2 
  shared_preferences: ^2.5.3
  google_sign_in_web: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/MainFont.ttf